name: VipinCI
on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: |
          pwd
          ls -a
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g eslint
          npm install jasmine-node -g
          npm i webpack-cli
          npm i webpack
      - name: Run Unit Test
        run: npm run test
      - name: Checking report
        run:  |
          ls -lrt /home/runner/work/vipin-ci/vipin-ci/reports
          echo "######################Time#################"
          date
        
      #- run: |
#           ls -a
#       - run: npm install -g eslint
#       - run: |
          
#           
        
#       - run: eslint ./ --fix
#       - run: eslint     
