name: VipinCI
on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: |
          pwd
          ls -a
      - run: npm ci
      - run: |
          ls -a
          npm install -g eslint
          eslint ./
